### ISSUE TITLE
Description of tokens in ReadMe

### ISSUE THREAD

**Issue by SDP190** [davidfowl/IdentityEndpointsSample#3]
Hi @davidfowl,

I have a misunderstanding in description you wrote in the ReadMe:

Quote:
> The tokens are self contained, and generated using the same technique as cookie authentication. These are NOT JWTs, they are opaque tokens

This statement seems contradicting, Jwt's = Self Containd , Opaque tokens = Reference Tokens (therefore arn't called "self-contained" since they don't have inside containing any id info, you have to check their value and validity in the server).

Please clarify if the tokens do hold info about the authenticated user. cause I do think that also the Cookie auth used by aspnetcore are self-contained, meaning they actually contain the properties of the authenticated user. correct?

**Comment by davidfowl** [comment]
The tokens hold user authentication data in an encrypted and signed self-contained token.

**Comment by SDP190** [comment]
@davidfowl thanks for quick response!

> The tokens hold user authentication data in an encrypted and signed self-contained token

How then would a client app holding the token, be able to decrypt the token in order to get logged in user info, like user name?

**Comment by davidfowl** [comment]
> How then would a client app holding the token, be able to decrypt the token in order to get logged in user info, like user name?

It can't, the client must call a server endpoint to get the user information.

**Comment by SDP190** [comment]
Got it, thanks again for clarifying, it really makes a big difference when know how things work.
